export type Product = {
  id: string;
  name: string;
  category: string;
  description: string;
  specifications?: string[];
  code?: string;
  image?: string;
  customizationAvailable: boolean;
  minimumOrder?: number;
  featured: boolean;
  active: boolean;
};

export const packagingImage = "/images/envases-marca.png";

export const categories = [
  { id: "individuales", name: "Regalos individuales", description: "Una pieza especial para cada persona." },
  { id: "copas", name: "Copas", description: "Sets artesanales para eventos y celebraciones." },
  { id: "hogar", name: "Sets para el hogar", description: "Regalos completos para disfrutar y compartir." },
  { id: "bar", name: "Sets de bar", description: "Combinaciones sofisticadas para clientes y VIPs." },
  { id: "premium", name: "Regalos premium", description: "Piezas seleccionadas para ocasiones especiales." },
];

export const products: Product[] = [
  // --- Individuales ---
  {
    id: "fernet",
    name: "Vaso Fernet",
    category: "individuales",
    description: "Una pieza artesanal de silueta ondulada, creada para convertirse en un regalo corporativo memorable.",
    code: "FER",
    image: "/images/vaso-fernet.png",
    customizationAvailable: true,
    minimumOrder: 25,
    featured: true,
    active: true,
  },
  {
    id: "decanter",
    name: "Decantador",
    category: "individuales",
    description: "Decantador de cuello estrecho y cuerpo amplio, pensado para airear y servir vino con elegancia.",
    specifications: ["Alto: 28 cm aprox.", "Diámetro: 17 cm aprox.", "Peso: 830 g aprox.", "Capacidad: 1.400 ml"],
    code: "DE",
    image: "/images/decantador.png",
    customizationAvailable: true,
    minimumOrder: 25,
    featured: true,
    active: true,
  },
  {
    id: "night",
    name: "Set de noche A",
    category: "individuales",
    description: "Una jarra compacta con un vaso que encaja en la parte superior, ideal para mesas de noche y escritorios.",
    specifications: ["Jarra: 15,5 cm · 700 ml", "Vaso: 7,5 cm · 130 ml"],
    code: "JNS + VJN",
    image: "/images/night-set-a.png",
    customizationAvailable: true,
    minimumOrder: 25,
    featured: true,
    active: true,
  },
  {
    id: "florero-fn",
    name: "Florero FN",
    category: "individuales",
    description: "Una pieza escultórica de vidrio artesanal para un regalo de presencia excepcional.",
    image: "/images/florero-fn.jpeg",
    specifications: ["Alto: 24 cm aprox.", "Diámetro máximo: 15 cm aprox.", "Peso: 1.300 g aprox.", "Capacidad: 2.850 ml"],
    code: "FN",
    customizationAvailable: true,
    minimumOrder: 25,
    featured: true,
    active: true,
  },
  {
    id: "vaso-bvv",
    name: "Vaso BVV",
    category: "individuales",
    description: "Vaso artesanal amplio, con gran presencia para bebidas frías, whisky o tragos de autor.",
    code: "BVV",
    image: "/images/vaso-bvv.jpeg",
    customizationAvailable: true,
    minimumOrder: 25,
    featured: false,
    active: true,
  },
  {
    id: "taza-t4g",
    name: "Vaso / Taza T4G",
    category: "individuales",
    description: "Diseño ergonómico y robusto en vidrio grueso artesanal para café o infusiones con identidad.",
    code: "T4G",
    image: "/images/taza-t4g.png",
    customizationAvailable: true,
    minimumOrder: 25,
    featured: false,
    active: true,
  },

  // --- Copas ---
  {
    id: "vkg",
    name: "Copa VKG",
    category: "copas",
    description: "Copa artesanal de gran capacidad y silueta contemporánea, ideal para vino o coctelería.",
    specifications: ["Alto: 23,4 cm aprox.", "Diámetro: 8 cm aprox.", "Capacidad: 500 ml"],
    code: "VKG",
    image: "/images/copa-vkg.jpeg",
    customizationAvailable: true,
    minimumOrder: 25,
    featured: true,
    active: true,
  },
  {
    id: "ch11",
    name: "Copa CH11",
    category: "copas",
    description: "Una copa estilizada y refinada para eventos corporativos y brindis especiales.",
    specifications: ["Alto: 19,5 cm aprox.", "Diámetro: 6 cm aprox.", "Capacidad: 190 ml"],
    code: "CH11",
    image: "/images/copa-ch11.jpeg",
    customizationAvailable: true,
    minimumOrder: 25,
    featured: false,
    active: true,
  },
  {
    id: "ch9",
    name: "Copa CH9",
    category: "copas",
    description: "Una copa equilibrada y versátil para regalos y eventos empresariales.",
    specifications: ["Alto: 17,2 cm aprox.", "Diámetro: 6 cm aprox.", "Capacidad: 360 ml"],
    code: "CH9",
    image: "/images/copa-ch9.jpeg",
    customizationAvailable: true,
    minimumOrder: 25,
    featured: true,
    active: true,
  },
  {
    id: "cf2",
    name: "Copa CF2",
    category: "copas",
    description: "Proporciones ligeras y elegantes en vidrio soplado artesanal.",
    specifications: ["Alto: 21 cm aprox.", "Diámetro: 6,5 cm aprox.", "Capacidad: 300 ml"],
    code: "CF2",
    image: "/images/copa-cf2.jpeg",
    customizationAvailable: true,
    minimumOrder: 25,
    featured: false,
    active: true,
  },
  {
    id: "bv",
    name: "Copa BV",
    category: "copas",
    description: "Una copa amplia y llamativa para bebidas, celebraciones y degustaciones.",
    specifications: ["Alto: 16 cm aprox.", "Diámetro: 8,5 cm aprox.", "Capacidad: 550 ml"],
    code: "BV",
    image: "/images/copa-bv.jpeg",
    customizationAvailable: true,
    minimumOrder: 25,
    featured: false,
    active: true,
  },

  // --- Sets para el Hogar ---
  {
    id: "set-rio-alto",
    name: "Set Río Alto",
    category: "hogar",
    description: "Conjunto artesanal de primera línea para el hogar o mesa de directorio. Distinción pura.",
    image: "/images/set-rio-alto.jpeg",
    customizationAvailable: true,
    minimumOrder: 25,
    featured: true,
    active: true,
  },
  {
    id: "jarra-noche",
    name: "Jarra de noche con vaso (Set A)",
    category: "hogar",
    description: "Jarra y vaso en un solo conjunto, un regalo cálido y útil para el día a día.",
    code: "JNS + VJN",
    image: "/images/night-set-a.png",
    customizationAvailable: true,
    minimumOrder: 25,
    featured: true,
    active: true,
  },
  {
    id: "jarra-jj4-vj4",
    name: "Set Jarra y Vaso JJ4",
    category: "hogar",
    description: "Jarra artesanal de vidrio acompañada de vaso a juego para reuniones y oficina.",
    code: "JJ4 + VJ4",
    image: "/images/jarra-jj4-vj4.png",
    customizationAvailable: true,
    minimumOrder: 25,
    featured: false,
    active: true,
  },

  // --- Sets de Bar ---
  {
    id: "set-whisky",
    name: "Set de Bar Whisky",
    category: "bar",
    description: "Vasos de whisky artesanales con cenicero o complementos de vidrio, listos para llevar tu logo grabado.",
    code: "BAR SET",
    image: "/images/set-bar.png",
    customizationAvailable: true,
    minimumOrder: 25,
    featured: true,
    active: true,
  },
  {
    id: "set-fernet",
    name: "Set Fernet Corporativo",
    category: "bar",
    description: "Vasos artesanales de silueta ondulada presentados en kit de celebración con tu marca.",
    image: "/images/regalos-fernetera.jpg",
    customizationAvailable: true,
    minimumOrder: 25,
    featured: true,
    active: true,
  },
  {
    id: "set-bv-sp",
    name: "Set Degustación BV & SP",
    category: "bar",
    description: "Set sofisticado para degustación en vidrio soplado artesanal para clientes y eventos exclusivos.",
    code: "BV + SP",
    image: "/images/set-bv-sp.png",
    customizationAvailable: true,
    minimumOrder: 25,
    featured: false,
    active: true,
  },

  // --- Premium ---
  {
    id: "florero-fn-caja",
    name: "Florero FN Edición Especial en Caja",
    category: "premium",
    description: "Pieza escultórica FN presentada en caja de regalo rígida con empaque corporativo de lujo.",
    code: "FN CAJA",
    image: "/images/florero-fn-caja.jpeg",
    customizationAvailable: true,
    minimumOrder: 25,
    featured: true,
    active: true,
  },
  {
    id: "premium-decanter",
    name: "Decantador Premium",
    category: "premium",
    description: "Nuestra pieza más elegante, personalizada con tu marca y presentada en empaque especial para ejecutivos y VIPs.",
    code: "DE",
    image: "/images/decantador.png",
    customizationAvailable: true,
    minimumOrder: 25,
    featured: true,
    active: true,
  },
];
